apiVersion: apps/v1
kind: Deployment
metadata:
  name: production-deployment
  labels:
    app: hello
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello-app
        image: us-east1-docker.pkg.dev/qwiklabs-gcp-01-7890e81814a4/my-repository/hello-app:v1.0
        ports:
        - containerPort: 8080
